// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
INSERT INTO feed_follows (id_feeds_follow, create_at,  user_id, feed_id)
VALUES ($1, $2, $3, $4)
RETURNING id_feeds_follow, create_at, user_id, feed_id
`

type CreateFeedFollowParams struct {
	IDFeedsFollow uuid.UUID
	CreateAt      time.Time
	UserID        uuid.UUID
	FeedID        uuid.UUID
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.IDFeedsFollow,
		arg.CreateAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollow
	err := row.Scan(
		&i.IDFeedsFollow,
		&i.CreateAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
