// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	IDFeeds   uuid.UUID
	CreatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.NullUUID
}

type User struct {
	ID      uuid.UUID
	Name    string
	Email   string
	Created time.Time
	ApiKey  string
}
