// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
CREATE EXTENSION IF NOT EXISTS pgcrypto
`

type CreateUserRow struct {
}

func (q *Queries) CreateUser(ctx context.Context) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i CreateUserRow
	err := row.Scan()
	return i, err
}
